# this is just used to trigger a copr rebuild

# NOTE: this an experimental build, stated in the description of this copr project,
# which means current build does not reflect final released build.
[package]
version = "0.10.0"
rebuilds = "2"
description = "trigger rebuild"



