blank_issues_enabled: false
contact_links:
  - name: Questions / Discussions
    url: https://github.com/vani-tty1/memerist/discussions
    about: For general questions, please use Discussions instead of an issue.