name: Build AppImage

on:
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y meson ninja-build libgtk-4-dev build-essential gettext appstream libadwaita-1-dev desktop-file-utils

    - name: Build and install to AppDir
      run: |
        meson setup build --prefix=/usr
        DESTDIR=AppDir meson install -C build

    - name: Download linuxdeploy and GTK plugin
      run: |
        wget -c "https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh"
        wget -c "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
        chmod +x linuxdeploy-x86_64.AppImage linuxdeploy-plugin-gtk.sh

    - name: Generate AppImage
      run: |
        export LDAI_OUTPUT="memerist-x86_64.AppImage"
        export DEPLOY_GTK_VERSION="4"
        ./linuxdeploy-x86_64.AppImage --appimage-extract
        ./squashfs-root/AppRun --appdir AppDir \
          -d AppDir/usr/share/applications/io.github.vani_tty1.memerist.desktop \
          -i AppDir/usr/share/icons/hicolor/scalable/apps/io.github.vani_tty1.memerist.svg \
          --plugin gtk --output appimage

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: memerist-AppImage
        path: memerist-x86_64.AppImage